- name: Remove file
  file:
    path: /var/www/html/index.html
    state: absent

- name: Create a directory
  file:
    path: /var/www/html/my_project
    state: directory
    mode: '0755'
  become: yes
  become_user: vagrant

- name: install symfony
  composer:
    command: create-project
    arguments: symfony/website-skeleton:^4.4 ./
    working_dir: /var/www/html/my_project
    prefer_dist: yes
  become: yes
  become_user: vagrant

- name: Compress directory
  archive:
    path: /var/www/html/my_project/
    dest: /var/www/html/my_project/compress.tgz
  become: yes
  become_user: vagrant

- name: Extract
  unarchive:
    src: /var/www/html/my_project/compress.tgz
    dest: /var/www/html
  become: yes
  become_user: vagrant


- name: Remove download
  file:
    path: /var/www/html/my_project
    state: absent

- name: Install orm-fixtures
  composer:
    command: require
    arguments: orm-fixtures
    no_dev: no
    working_dir: /var/www/html
  become: yes
  become_user: vagrant

- name: add subdomaine
  template:
    src: default.j2
    dest: "/etc/apache2/sites-available/000-default.conf"


- name: restart apache2
  service:
    name: "apache2"
    state: restarted


- name: Reglage base de données user
  replace:
    path: /var/www/html/.env
    regexp: 'db_user'
    replace: '{{ dbuser }}'

- name: Reglage base de données password
  replace:
    path: /var/www/html/.env
    regexp: 'db_password'
    replace: '{{ pwduserdb }}'

- name: Reglage base de données dbname
  replace:
    path: /var/www/html/.env
    regexp: 'db_name'
    replace: '{{dbname}}'

- name: Reglage base de données version
  replace:
    path: /var/www/html/.env
    regexp: '5.7'
    replace: 'mariadb-10.4.12'

- name: Install webpack encore
  composer:
    command: require
    arguments: symfony/webpack-encore-bundle
    no_dev: no
    working_dir: /var/www/html
  become: yes
  become_user: vagrant

- name: This command will change the working directory to somedir/.
  shell:
    cmd: yarn install --no-bin-links
    chdir: /var/www/html
  become: yes
  become_user: vagrant

- name: Install sass-loader if true.
  shell:
    cmd: yarn add sass-loader node-sass --no-bin-links
    chdir: /var/www/html
  when: "{{ installSassLoader }} == true"
  become: yes
  become_user: vagrant

- name: Change path for machine virtual symboliklink
  replace:
    path: /var/www/html/package.json
    regexp: '"dev-server": "encore dev-server"'
    replace: '"dev-server": "./node_modules/@symfony/webpack-encore/bin/encore.js dev-server"'
  when: "{{ installSassLoader }} == true"
  become: yes
  become_user: vagrant

- name: Change path for machine virtual symboliklink
  replace:
    path: /var/www/html/package.json
    regexp: '"dev": "encore dev"'
    replace: '"dev": "./node_modules/@symfony/webpack-encore/bin/encore.js dev"'
  when: "{{ installSassLoader }} == true"
  become: yes
  become_user: vagrant

- name: Change path for machine virtual symboliklink
  replace:
    path: /var/www/html/package.json
    regexp: '"watch": "encore dev --watch"'
    replace: '"watch": "./node_modules/@symfony/webpack-encore/bin/encore.js dev --watch"'
  when: "{{ installSassLoader }} == true"
  become: yes
  become_user: vagrant

- name: Change path for machine virtual symboliklink
  replace:
    path: /var/www/html/package.json
    regexp: '"build": "encore production --progress"'
    replace: '"build": "./node_modules/@symfony/webpack-encore/bin/encore.js production --progress"'
  when: "{{ installSassLoader }} == true"
  become: yes
  become_user: vagrant
